server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graduation_project?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    cache: off
    mode: LEGACYHTML5
    check-template: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8

  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/**
  web:
    resources:
      chain:
        enabled: true
        strategy:
          content:
            paths: /**


mybatis:
  type-aliases-package: wangkai.graduationProject.entity
